// Single source of truth for ROTEX cloud models.
// Cloud models route through OpenRouter. Ollama is local-only in the client.

const MODELS = {
  gbt: {
    name: 'GBT',
    maker: 'gbt',
    logo: 'G',
    tier: 'free',
    cost: 0.004,
    computerCost: 0.012,
    route: 'openrouter',
    orModel: 'openai/gpt-4o-mini',
    blurb: 'Fast OpenAI GPT model through OpenRouter.',
    maxTokens: 2048,
    proMaxTokens: 4096,
  },
  groq: {
    name: 'Groq',
    maker: 'groq',
    logo: 'Q',
    tier: 'free',
    cost: 0.002,
    computerCost: 0.01,
    route: 'openrouter',
    orModel: 'meta-llama/llama-3.3-70b-instruct',
    blurb: 'Fast model routed through OpenRouter.',
    maxTokens: 2048,
    proMaxTokens: 4096,
  },
  gemini: {
    name: 'Gemini',
    maker: 'gemini',
    logo: 'Ge',
    tier: 'free',
    cost: 0.003,
    computerCost: 0.01,
    route: 'openrouter',
    orModel: 'google/gemini-2.5-flash-lite',
    blurb: 'Gemini through OpenRouter for quick answers and long context.',
    maxTokens: 2048,
    proMaxTokens: 4096,
  },
  deepseek: {
    name: 'DeepSeek',
    maker: 'deepseek',
    logo: 'D',
    tier: 'free',
    cost: 0.004,
    computerCost: 0.012,
    route: 'openrouter',
    orModel: 'deepseek/deepseek-chat',
    blurb: 'DeepSeek through OpenRouter for coding and general work.',
    maxTokens: 2048,
    proMaxTokens: 8192,
  },
  'claude-sonnet': {
    name: 'Claude Sonnet',
    maker: 'claude',
    logo: 'CS',
    tier: 'pro',
    cost: 0.4,
    computerCost: 0.8,
    route: 'anthropic-first',
    envModel: 'CLAUDE_SONNET_MODEL',
    anthropicModel: 'claude-sonnet-4-5',
    orModel: 'anthropic/claude-sonnet-4.5',
    blurb: 'Expensive Pro model for careful project work and bigger fixes.',
    maxTokens: 8192,
    proMaxTokens: 8192,
  },
  'claude-opus': {
    name: 'Claude Opus',
    maker: 'claude',
    logo: 'CO',
    tier: 'pro',
    cost: 0.75,
    computerCost: 1.5,
    route: 'anthropic-first',
    envModel: 'CLAUDE_OPUS_MODEL',
    anthropicModel: 'claude-opus-4-1',
    orModel: 'anthropic/claude-opus-4.1',
    blurb: 'Most expensive Claude option for hard architecture, debugging, and agent planning.',
    maxTokens: 8192,
    proMaxTokens: 8192,
  },
  'grok-3-4': {
    name: 'Grok 3.4',
    maker: 'grok',
    logo: 'X',
    tier: 'pro',
    cost: 0.45,
    computerCost: 0.9,
    route: 'openrouter',
    orModel: process.env.GROK_3_4_MODEL || 'x-ai/grok-3.4',
    blurb: 'Expensive Pro reasoning model for broad context and hard decisions.',
    maxTokens: 4096,
    proMaxTokens: 8192,
  },
  'gbt-5-5': {
    name: 'GBT 5.5',
    maker: 'gbt',
    logo: 'G5',
    tier: 'pro',
    cost: 0.7,
    computerCost: 1.4,
    route: 'openrouter',
    orModel: process.env.GBT_5_5_MODEL || 'openai/gpt-5.5',
    blurb: 'Very expensive Pro smart model for frontier-level tasks.',
    maxTokens: 8192,
    proMaxTokens: 8192,
  },
  'deepseek-smart': {
    name: 'DeepSeek Smartest',
    maker: 'deepseek',
    logo: 'DS',
    tier: 'pro',
    cost: 0.3,
    computerCost: 0.6,
    route: 'openrouter',
    orModel: process.env.DEEPSEEK_SMARTEST_MODEL || 'deepseek/deepseek-r1',
    blurb: 'Expensive Pro DeepSeek model for the smartest code and reasoning tasks.',
    maxTokens: 8192,
    proMaxTokens: 8192,
  },
};

const LOCAL_MODELS = {
  ollama: {
    name: 'Ollama',
    maker: 'ollama',
    logo: 'O',
    tier: 'free',
    cost: 0,
    computerCost: 0,
    blurb: 'Local model running on your own PC.',
    localOnly: true,
  },
};

const MODEL_ALIASES = {
  'llama-3-3-70b': 'groq',
  'deepseek-v3': 'deepseek',
  'deepseek-r1': 'deepseek-smart',
  'deepseek-smartest': 'deepseek-smart',
  'deepseek-smart': 'deepseek-smart',
  'gemini-flash-lite': 'gemini',
  'gemini-flash': 'gemini',
  'gemini-pro': 'gemini',
  'gpt-4o-mini': 'gbt',
  'gpt-4o': 'gbt',
  'gpt-5-1': 'gbt-5-5',
  'gpt-5-1-codex': 'gbt-5-5',
  'gpt-5-2': 'gbt-5-5',
  'gpt-5-5': 'gbt-5-5',
  'gbt-5.5': 'gbt-5-5',
  'gbt-5-5': 'gbt-5-5',
  o3: 'gbt',
  'o4-mini': 'gbt',
  claude: 'claude-sonnet',
  'claude-haiku': 'claude-sonnet',
  'claude-sonnet': 'claude-sonnet',
  'claude-opus': 'claude-opus',
  'claude-fable': 'claude-sonnet',
  grok: 'grok-3-4',
  'grok-3.4': 'grok-3-4',
  'grok-3-4': 'grok-3-4',
  'qwen-flash': 'gbt',
  'qwen-max': 'gbt',
  codestral: 'gbt',
  'mistral-large': 'gbt',
  'rod-1': 'groq',
  'rod-thinking': 'deepseek',
  'rod-brain': 'claude-sonnet',
  'tex-0': 'deepseek',
  'tex-1-5': 'claude-sonnet',
  'tex-2': 'gbt-5-5',
  'tex-2-5': 'claude-opus',
  'treesearch-q': 'deepseek-smart',
  'ron-1-lite': 'groq',
  'ron-1-hard': 'deepseek',
  'rreas-2-1': 'deepseek',
  'rtrox-cheap': 'claude-sonnet',
  'rtrox-1-8': 'claude-sonnet',
  'rtrox-3': 'claude-opus',
  'rtrox-hard': 'claude-opus',
};

const DEFAULT_MODEL_ID = 'gbt';

function resolveModelId(id) {
  if (MODELS[id]) return id;
  if (MODEL_ALIASES[id] && MODELS[MODEL_ALIASES[id]]) return MODEL_ALIASES[id];
  return DEFAULT_MODEL_ID;
}

function publicCatalog() {
  return Object.entries({ ...MODELS, ...LOCAL_MODELS }).map(([id, m]) => ({
    id,
    name: m.name,
    maker: m.maker,
    logo: m.logo,
    tier: m.tier,
    cost: m.cost,
    computerCost: m.computerCost ?? null,
    blurb: m.blurb,
    localOnly: Boolean(m.localOnly),
    best: Boolean(m.best),
  }));
}

module.exports = { MODELS, LOCAL_MODELS, MODEL_ALIASES, DEFAULT_MODEL_ID, resolveModelId, publicCatalog };
